#ExamAssistancePlugin

Setting:
  CategoryId: 000000000000
  AdviserRoleId: 000000000000
  JudgeRoleId: 0000000000
  Message:
    ExamStart:
      color: 'GREEN'
      title: 'ようこそ'
      description: 'これは自動送信メッセージです。'
      image: 'https://crafatar.com/avatars/%uuid%'
      timestamp: true
      message:
        - 'ようこそ'
        - 'これはデフォルトメッセージです。'

Discord:
  CreateTicketChannel: false
  ChannelCategory: 0000000000
  ChangeNickName: false

SendMessage:
    message:

